# This is a compose file for running tests only.
version: "3"
services:
  postgres:
    container_name: zsharp-postgres
    image: postgres:12
    ports:
    - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
